INSERT INTO TBL_CATEGORY (NAME) VALUES ('Fabricação Própria')
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Nacional')
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Importado')
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Premium')

INSERT INTO TBL_PRODUCT (NAME, PRICE, DESCRIPTION, CATEGORY_ID, PROMOTION, NEW_PRODUCT) VALUES ('Teclado mecânico RGB', 100, 'Descrição Teclado mecânico RGB', 1, TRUE, TRUE)
INSERT INTO TBL_PRODUCT (NAME, PRICE, DESCRIPTION, CATEGORY_ID, PROMOTION, NEW_PRODUCT) VALUES ('Mouse sem fio ergonômico', 200, 'Descrição Mouse sem fio ergonômico', 2, TRUE, FALSE)
INSERT INTO TBL_PRODUCT (NAME, PRICE, DESCRIPTION, CATEGORY_ID, PROMOTION, NEW_PRODUCT) VALUES ('Monitor ultrawide curvo', 300, 'Descrição Monitor ultrawide curvo', 3, FALSE, TRUE)
INSERT INTO TBL_PRODUCT (NAME, PRICE, DESCRIPTION, CATEGORY_ID, PROMOTION, NEW_PRODUCT) VALUES ('SSD NVMe de alta velocidade', 400, 'Descrição SSD NVMe de alta velocidade', 4, FALSE, FALSE)